SYSTEM_NAME="cave"
SYSTEM_FULLNAME="Cave"
SYSTEM_MANUFACTURER="CAVE Interactive Co., Ltd."
SYSTEM_RELEASE="1994"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/cave"
SYSTEM_EXTENSION=".7z .zip"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="cave"
