SYSTEM_NAME="neogeo-mvs"
SYSTEM_FULLNAME="Neo Geo MVS"
SYSTEM_MANUFACTURER="SNK Corporation"
SYSTEM_RELEASE="1990"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/neogeo-mvs"
SYSTEM_EXTENSION=".7z .zip"
SYSTEM_PLATFORM="neogeo-mvs"
SYSTEM_THEME="neogeo"
SYSTEM_WIKI_PATH="neogeo-mvs"
