SYSTEM_NAME="neogeo-aes"
SYSTEM_FULLNAME="Neo Geo AES"
SYSTEM_MANUFACTURER="SNK Corporation"
SYSTEM_RELEASE="1990"
SYSTEM_HARDWARE="console"
SYSTEM_PATH="/storage/roms/neogeo-aes"
SYSTEM_EXTENSION=".7z .zip .neo"
SYSTEM_PLATFORM="neogeo-aes"
SYSTEM_THEME="neogeo"
SYSTEM_WIKI_PATH="neogeo-aes"
