SYSTEM_NAME="nichibutsu"
SYSTEM_FULLNAME="Nichibutsu"
SYSTEM_MANUFACTURER="Nihon Bussan Co. Ltd."
SYSTEM_RELEASE="1978"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/nichibutsu"
SYSTEM_EXTENSION=".7z .zip"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="nichibutsu"
SYSTEM_WIKI_PATH="nichibutsu"
