SYSTEM_NAME="nintendo"
SYSTEM_FULLNAME="Nintendo"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="1978"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/nintendo"
SYSTEM_EXTENSION=".zip .7z"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="nintendo"
SYSTEM_WIKI_PATH="nintendo"
