SYSTEM_NAME="nintendo-arcade"
SYSTEM_FULLNAME="Nintendo Arcade"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="1978"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/nintendo-arcade"
SYSTEM_EXTENSION=".zip .7z"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="nes"
SYSTEM_WIKI_PATH="nintendo-arcade"
