SYSTEM_NAME="playch-10"
SYSTEM_FULLNAME="PlayChoice-10"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="1986"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/playch-10"
SYSTEM_EXTENSION=".7z .zip"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="playch-10"
