SYSTEM_NAME="vsnes"
SYSTEM_FULLNAME="Nintendo VS. System"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="1984"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/vsnes"
SYSTEM_EXTENSION=".7z .zip"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="vsnes"
SYSTEM_WIKI_PATH="vsnes"
